export const TIMESLOT_STATUS_NEEDS_APPROVE = 0;
export const TIMESLOT_STATUS_APPROVED = 10;
export const TIMESLOT_STATUS_NEEDS_MENTOR = TIMESLOT_STATUS_APPROVED;
export const TIMESLOT_STATUS_MENTOR_NEEDS_APPROVE = 15;
export const TIMESLOT_STATUS_HAS_MENTOR = 20;
export const TIMESLOT_STATUS_REJECTED = 30;
