language: node_js
node_js:
- 8
install:
- yarn
env:
  secure: QQYzYwWpv8WSnScsM8V6fnYMT7A4EWAFHkX8AFl1lDhArY7WtuJozs9Uy9937yR6SzEwkifUQvRoIud/wsYbRuXfzhgwKW0VA0DlW0CnGH9DVPHw9PkKfDjyq89FybD2K0QGWUsZbHQ5AYCbbiql0OhX2MPQi8mj9QlHlA8ftd1KaPHwx5suDIrE9qH9aBarVWrJzNtqetRxj8F60Hq/oG9FmeYD7NLi/rUo+xI0k6/C1wwEF7rHq/u3FCCFaZ9fCh6D09Vz0SBzhami4PZAnhCajY2iqdg33uT8O4W87yQcHScZbeZQiq09FPlA1RibnCC1ImnVOaZmyT+hge7/ndU/tJYzAif6FIrFjNqrF/QdmbH+ZKS2nunfD8iAmJ1vs8+ZsmEholSc7yK70ZvyfRWU1l5ZqIsbm6EUloXAazMAB7FirG5vMSvZThQt0Qu4yVXY5QqqcCXfoPylpeO2+IO/+C/8fVALxYP78HlzJinm5/T3ur6HQkpikEuhtFnMH/xaSoUWHXYPiVA23nmnVOYXwgQaJmYtXjU/zo2GcdKQ920sDIben0LfXgeFSpwrsASLNXYqnHvEh6qcisF93z/3VmBz/NSdpSpbKsOfuqpdLFlqynr/8VI9DjELrQBU0f2PSaFTLrjUsK/NwfSLnB68c7iQWTyAc9ZetM/24So=

script:
  - echo "Running unit tests!"
  - yarn test
  - echo "Pushing coverage to Codacy!"
  - yarn codacy

# jobs:
#   include:
#     - stage: Test
#       script: yarn test
#     - stage: Push coverage to Codacy
#       script: yarn codacy
