language: node_js
node_js: 8
install:
- yarn
- cd functions && yarn && cd ..
cache:
  directories:
  - node_modules
  - functions/node_modules

env:
  secure: QQYzYwWpv8WSnScsM8V6fnYMT7A4EWAFHkX8AFl1lDhArY7WtuJozs9Uy9937yR6SzEwkifUQvRoIud/wsYbRuXfzhgwKW0VA0DlW0CnGH9DVPHw9PkKfDjyq89FybD2K0QGWUsZbHQ5AYCbbiql0OhX2MPQi8mj9QlHlA8ftd1KaPHwx5suDIrE9qH9aBarVWrJzNtqetRxj8F60Hq/oG9FmeYD7NLi/rUo+xI0k6/C1wwEF7rHq/u3FCCFaZ9fCh6D09Vz0SBzhami4PZAnhCajY2iqdg33uT8O4W87yQcHScZbeZQiq09FPlA1RibnCC1ImnVOaZmyT+hge7/ndU/tJYzAif6FIrFjNqrF/QdmbH+ZKS2nunfD8iAmJ1vs8+ZsmEholSc7yK70ZvyfRWU1l5ZqIsbm6EUloXAazMAB7FirG5vMSvZThQt0Qu4yVXY5QqqcCXfoPylpeO2+IO/+C/8fVALxYP78HlzJinm5/T3ur6HQkpikEuhtFnMH/xaSoUWHXYPiVA23nmnVOYXwgQaJmYtXjU/zo2GcdKQ920sDIben0LfXgeFSpwrsASLNXYqnHvEh6qcisF93z/3VmBz/NSdpSpbKsOfuqpdLFlqynr/8VI9DjELrQBU0f2PSaFTLrjUsK/NwfSLnB68c7iQWTyAc9ZetM/24So=

  # global:
  #   secure: SpEBtQzY6JrzifQ88+fc7gnbmvbNQBkSGvnbsQm/E5JPX6NUUc9FLNRbLQSxBIhK37IAJa4eSL+kivQKxZESAMQxSM7wxaAGxfxcdrx+94JKFVO2MQpoombqvKqhObJ6n27c0K8JPWvYyQUAbtI6TxCOJxoE511qDjBMxN+b+Cx2k1MZOj1A5rmq1v7Sko8U/A8EJd1mShU6hovns207QfrXzxZlrApUehMX3d3Pcj5JqHYJ7NJzY5hKkxCuVLNpyNQfwmpEjqfe1tBanjpl0Tdacu2Geix77QfQOy5xMstv2g+1URxqGnrb7Tr5K0KA3sog1Kpr662NmBsL91MKUk7UcKFPhVv9nDmmHcU2pKQszNsZCoPKl4zgbgvAfrJngwYBAriVyu4s0uQj7DHNKCOXtTM+ly6bthOX+DRHhsTeXVaaqZe+NsRU66tifdzdaDUgjSiwg3mtHc+L9FcKQBZFkqDU6H+RcY7YeIJXTPYvFaJzIdnC8uTQYBiR9hykFD0MOYud9GsB6WoZ2BC2jqSvvbCi80tvrwiOGNYgNRQPLFUo9QGQGZWA11q4jDn/U6ibKyhjP0LzboiWZjTBPqRyfI77Dd+wdj+q7bJpMKLCwgCt87flN94rS2SLAdAcA9dFBCqBZJkWuFGC/yuLRATJcG1+clxAdg0y7QAS85A=

jobs:
  include:
  - stage: test
    script:
    - yarn lint
    - yarn test
  - stage: Codacy
    script: yarn test && yarn codacy
  - stage: Build
    script: yarn build
    env: SpEBtQzY6JrzifQ88+fc7gnbmvbNQBkSGvnbsQm/E5JPX6NUUc9FLNRbLQSxBIhK37IAJa4eSL+kivQKxZESAMQxSM7wxaAGxfxcdrx+94JKFVO2MQpoombqvKqhObJ6n27c0K8JPWvYyQUAbtI6TxCOJxoE511qDjBMxN+b+Cx2k1MZOj1A5rmq1v7Sko8U/A8EJd1mShU6hovns207QfrXzxZlrApUehMX3d3Pcj5JqHYJ7NJzY5hKkxCuVLNpyNQfwmpEjqfe1tBanjpl0Tdacu2Geix77QfQOy5xMstv2g+1URxqGnrb7Tr5K0KA3sog1Kpr662NmBsL91MKUk7UcKFPhVv9nDmmHcU2pKQszNsZCoPKl4zgbgvAfrJngwYBAriVyu4s0uQj7DHNKCOXtTM+ly6bthOX+DRHhsTeXVaaqZe+NsRU66tifdzdaDUgjSiwg3mtHc+L9FcKQBZFkqDU6H+RcY7YeIJXTPYvFaJzIdnC8uTQYBiR9hykFD0MOYud9GsB6WoZ2BC2jqSvvbCi80tvrwiOGNYgNRQPLFUo9QGQGZWA11q4jDn/U6ibKyhjP0LzboiWZjTBPqRyfI77Dd+wdj+q7bJpMKLCwgCt87flN94rS2SLAdAcA9dFBCqBZJkWuFGC/yuLRATJcG1+clxAdg0y7QAS85A=
    # env: FIREBASE_API_KEY=AIzaSyBwBtareu_jsCdeRK4S2LP-QFxHUWKygnU FIREBASE_AUTH_DOMAIN=hoc-org-dev.firebaseapp.com
    #   FIREBASE_DATABASE_URL=https://hoc-org-dev.firebaseio.com FIREBASE_PROJECT_ID=hoc-org-dev
    #   FIREBASE_STORAGE_BUCKET=hoc-org-dev.appspot.com FIREBASE_MESSAGING_SENDER_ID=281059038812
    #   GOOGLE_MAPS_KEY=AIzaSyCR472mBTvr5hvtF99xZHaEgLXw34x
