export const APPROVE_TIMESLOTS = 'app/Admin/Timeslots/APPROVE_TIMESLOTS';
export const APPROVE_TIMESLOTS_FAILURE = 'app/Admin/Timeslots/APPROVE_TIMESLOTS_FAILURE';
export const APPROVE_TIMESLOTS_SUCCESS = 'app/Admin/Timeslots/APPROVE_TIMESLOTS_SUCCESS';
export const DELETE_TIMESLOT = 'app/Admin/Timeslots/DELETE_TIMESLOT';
export const DELETE_TIMESLOT_FAILURE = 'app/Admin/Timeslots/DELETE_TIMESLOT_FAILURE';
export const DELETE_TIMESLOT_SUCCESS = 'app/Admin/Timeslots/DELETE_TIMESLOT_SUCCESS';
export const FETCH_TIMESLOTS = 'app/Admin/Timeslots/FETCH_TIMESLOTS';
export const FETCH_TIMESLOTS_FAILURE = 'app/Admin/Timeslots/FETCH_TIMESLOTS_FAILURE';
export const FETCH_TIMESLOTS_SUCCESS = 'app/Admin/Timeslots/FETCH_TIMESLOTS_SUCCESS';

export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS = 'app/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS';
export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS_FAILURE = 'app/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS_FAILURE';
export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS_SUCCESS = 'app/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS_SUCCESS';
