export const APPROVE_TIMESLOTS = 'app/Users/Admin/Timeslots/APPROVE_TIMESLOTS';
export const APPROVE_TIMESLOTS_FAILURE = 'app/Users/Admin/Timeslots/APPROVE_TIMESLOTS_FAILURE';
export const APPROVE_TIMESLOTS_SUCCESS = 'app/Users/Admin/Timeslots/APPROVE_TIMESLOTS_SUCCESS';
export const FETCH_TIMESLOTS = 'app/Users/Admin/Timeslots/FETCH_TIMESLOTS';
export const FETCH_TIMESLOTS_FAILURE = 'app/Users/Admin/Timeslots/FETCH_TIMESLOTS_FAILURE';
export const FETCH_TIMESLOTS_SUCCESS = 'app/Users/Admin/Timeslots/FETCH_TIMESLOTS_SUCCESS';

export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS = 'app/Users/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS';
export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS_FAILURE = 'app/Users/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS_FAILURE';
export const WIDGET_FETCH_UNAPPROVED_TIMESLOTS_SUCCESS = 'app/Users/Admin/Timeslots/WIDGET_FETCH_UNAPPROVED_TIMESLOTS_SUCCESS';
