export const CREATE_SCHOOL = 'app/Schools/CREATE_SCHOOL';
export const CREATE_SCHOOL_FAILURE = 'app/Schools/CREATE_SCHOOL_FAILURE';
export const CREATE_SCHOOL_SUCCESS = 'app/Schools/CREATE_SCHOOL_SUCCESS';

export const DELETE_SCHOOL = 'app/Schools/DELETE_SCHOOL';
export const DELETE_SCHOOL_FAILURE = 'app/Schools/DELETE_SCHOOL_FAILURE';
export const DELETE_SCHOOL_SUCCESS = 'app/Schools/DELETE_SCHOOL_SUCCESS';

export const FETCH_SCHOOL = 'app/Schools/FETCH_SCHOOL';
export const FETCH_SCHOOL_FAILURE = 'app/Schools/FETCH_SCHOOL_FAILURE';
export const FETCH_SCHOOL_SUCCESS = 'app/Schools/FETCH_SCHOOL_SUCCESS';

export const FETCH_SCHOOL_TIMESLOTS = 'app/Schools/FETCH_SCHOOL_TIMESLOTS';
export const FETCH_SCHOOL_TIMESLOTS_FAILURE = 'app/Schools/FETCH_SCHOOL_TIMESLOTS_FAILURE';
export const FETCH_SCHOOL_TIMESLOTS_SUCCESS = 'app/Schools/FETCH_SCHOOL_TIMESLOTS_SUCCESS';

export const FETCH_SCHOOLS = 'app/Schools/FETCH_SCHOOLS';
export const FETCH_SCHOOLS_FAILURE = 'app/Schools/FETCH_SCHOOLS_FAILURE';
export const FETCH_SCHOOLS_SUCCESS = 'app/Schools/FETCH_SCHOOLS_SUCCESS';

export const UPDATE_SCHOOL = 'app/Schools/UPDATE_SCHOOL';
export const UPDATE_SCHOOL_FAILURE = 'app/Schools/UPDATE_SCHOOL_FAILURE';
export const UPDATE_SCHOOL_SUCCESS = 'app/Schools/UPDATE_SCHOOL_SUCCESS';

export const SCHOOL_FORM_ID = 'app/Schools/SCHOOL_FORM_ID';
