export const CREATE_TIMESLOT = 'app/Schedule/CREATE_TIMESLOT';
export const CREATE_TIMESLOT_FAILURE = 'app/Schedule/CREATE_TIMESLOT_FAILURE';
export const CREATE_TIMESLOT_SUCCESS = 'app/Schedule/CREATE_TIMESLOT_SUCCESS';

export const FETCH_TIMESLOTS = 'app/Schedule/FETCH_TIMESLOTS';
export const FETCH_TIMESLOTS_FAILURE = 'app/Schedule/FETCH_TIMESLOTS_FAILURE';
export const FETCH_TIMESLOTS_SUCCESS = 'app/Schedule/FETCH_TIMESLOTS_SUCCESS';

export const CREATE_TIMESLOT_FORM_ID = 'app/Schedule/CREATE_TIMESLOT_FORM_ID';
